### ISSUE TITLE
it is very SHIT

### ISSUE THREAD

**Issue by webbrowser11** [Baconing/ballos#1]
just a comment, did you think about 64-bit?

**Comment by Baconing** [comment]
wdym?

**Comment by webbrowser11** [comment]
like are you of 64-bit or 32-bit or both? someone might have a computer that only supports 64-bit someone else might have one that supports 32-bit

**Comment by Baconing** [comment]
currently 64 bit, more architectures will be implemented after 64 bit is done

project is on the backburner right now while i work on other things

**Comment by webbrowser11** [comment]
k thanks for adding 32-bit later gimme the iso when its ready!
